### ISSUE TITLE
CSS code style

### ISSUE THREAD

**Issue by berkandirim** [nuxt-community/pwa-template#10]
I see that opening braces are placed in a new line rather than the same line with a space. Please consider using the suggested style.
```
selector {
```

instead of 
```
selector
{
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c7">#c7</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Thanks for report. Would you please make a PR for this?

**Comment by berkandirim** [comment]
I did. Sorry I didn't realize the source was the starter template.
