### ISSUE TITLE
on npm install WARN: deprecated babel-preset-es2015@6.24.1 - recommend using babel-preset-env now

### ISSUE THREAD

**Issue by jamesray** [nuxt-community/pwa-template#13]
🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c9">#c9</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. This dependency is from nuxt which will be resolved which next rc (`rca`)

**Comment by jamesray** [comment]
@pi0   Thanks, good to know!
