### ISSUE TITLE
This repository template still on progress or not ?

### ISSUE THREAD

**Issue by rizkiheryandi** [nuxt-community/pwa-template#14]
Even, no service worker register when i run the template

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c12">#c12</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Are you running nuxt in dev mode? This template basically should works, only dependencies in package.json may be upgraded :)

**Comment by bovas85** [comment]
Try generating a static site, upload to an HTTPS enabled hosting (or use surge after npm i -g surge) and try from there.

Alternatively, build it and run now (npm i -g now first) to upload it there as nodejs app and it should also work

**Comment by bovas85** [comment]
@pi0 does this work no matter what we add to it in the nuxt template? (ie. new plugins and so on)

Also, how do we cache ajax requests?

**Comment by colsen1991** [comment]
@bovas85 
```
  workbox: {
    handleFetch: true
  }
 ```
in `nuxt.config.js` works fine for caching ajax requests. Keep in mind that the `@nuxtjs/pwa` dependency needs to be version 2 or higher for it to work.

And can confirm that it works just fine with a big range of modules and plugins. If you need to tweak the caching of the PWA module, have a look at the documentation for that (https://github.com/nuxt-community/pwa-module) and workbox (https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#abstract-types).

Hope this helps :)

**Comment by bovas85** [comment]
Thanks @colsen1991
