### ISSUE TITLE
ServiceWorker doesn't serve application when offline

### ISSUE THREAD

**Issue by buhrmi** [nuxt-community/pwa-template#2]
Hello,

When running this and visiting the website while online, the service worker is installed just fine. But when visiting the site while being offline, the service worker does not serve the application. Maybe I'm missing something, but shouldn't one benefit of service workers be that the application is available even though the user is offline?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c1">#c1</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi, Yes it should be able serving offline. I think that's because you are not testing production version over HTTPS.

**Comment by lewebsimple** [comment]
I can confirm the if works offline OOTB on heroku using HTTPS, while HTTP doesn't work.
