### ISSUE TITLE
Updating offline cache files

### ISSUE THREAD

**Issue by lewebsimple** [nuxt-community/pwa-template#3]
I'm wondering if updates to the cached files are handled automatically / semi-automatically with version number?
Could [this](https://workboxjs.org/reference-docs/latest/module-workbox-broadcast-cache-update.html) be integrated?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c5">#c5</a>)</em></sub></div>

**Comment by pi0** [comment]
@lewebsimple This template leverages [workbox](https://github.com/nuxt-community/modules/tree/master/modules/workbox) and it internally uses [workbox webpack](https://github.com/nuxt-community/modules/blob/master/modules/workbox/index.js#L29). Not sure if it currently supports broadcast please open issue in either workbox or module's repo if enhancenment is possible. 
Thanks :)
