### ISSUE TITLE
How to redirect to HTTPS

### ISSUE THREAD

**Issue by PiusNyakoojo** [nuxt-community/pwa-template#4]
How can you setup forced https redirects? Thank you!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c2">#c2</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey.
Option 1: Using cloud providers always with on HTTPS feature. (like cloudflare)
Option 2: Using a global middleware like this: https://github.com/nuxt/hackernews/blob/master/middleware/https.js

**Comment by PiusNyakoojo** [comment]
Sweet, thank you :)
