### ISSUE TITLE
How to add custom code to ServiceWorker

### ISSUE THREAD

**Issue by buhrmi** [nuxt-community/pwa-template#5]
I can't find a way to add custom code (eg push notifications, etc.) to the service worker when using the pwa (workbox) nuxt module. Is there a way?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c4">#c4</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. Last time I've checked workbox web pack plugin there was no easy way unless writing a custom sw.js template. But try to investigate more possible ways soon :)

**Comment by buhrmi** [comment]
How about changing the module to the [workbox-build-webpack-plugin](https://workboxjs.org/reference-docs/latest/module-workbox-webpack-plugin.html) instead of the normal workbox-webpack-plugin?

**Comment by buhrmi** [comment]
ah, wait, it's the same ... just got confused because I saw it has a `swSrc` config options and workbox-webpack-plugin didn't have it

**Comment by buhrmi** [comment]
Closing this because my last comments don't make sense. Will open a more eloquent issue later.
