### ISSUE TITLE
WorkboxError: An error was thrown by workbox with error code: ;'request-not-cached' with extras:

### ISSUE THREAD

**Issue by marcosgallardo** [nuxt-community/pwa-template#8]
Hi everybody,

I'm getting this errors while navigating this template with only an extra page (`eg: about.vue`).

![image](https://user-images.githubusercontent.com/4549886/28894739-203a77a8-77ac-11e7-8aff-ca92512d9890.png)

Steps to reproduce them:

1. Exec `npm run build`

![image](https://user-images.githubusercontent.com/4549886/28894706-ff36c156-77ab-11e7-9a9c-5ac684779e36.png)

2. Exec `npm run start`

The server cannot found the `index.spa.html, index.ssr.html and vue-ssr-client-manifest.json` files, but those files exists in the `dist` folder. 

Any thoughts?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-template/issues/c8">#c8</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. This problem is due to rc3 upgrade. Please upgrade your dependencies to the lastest version (workbox@1.1.3)

**Comment by ghost** [comment]
Still a problem on a fresh install.
